GET /api/2.4/auctions/d841422b93d243be873935c64d9b04c5/awards/d70ffc5e83e14d02963ce093b2689b9b HTTP/1.0
Authorization: Basic YnJva2VyMzo=
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "dateModified": "2018-06-11T11:16:58.228559+03:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "auction protocol", 
        "author": "auction_owner", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/2355460e763d45d793a3e5f20296dd44?KeyID=172d32c8&Signature=k5pdoN7oM7wqqwSN8Chf2NTB4zMu71Cp12fkBC9%2FRqpqDvGYpsln7fEKcqsz1NJWubPIvs%2Fw9bv6XW3cf0OKDg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-06-11T11:16:58.228528+03:00", 
        "documentType": "auctionProtocol", 
        "title": "auction_protocol.pdf", 
        "id": "b5e4e116ed264e668592a1c84a777dc6"
      }
    ], 
    "verificationPeriod": {
      "startDate": "2018-06-11T11:16:58.058569+03:00", 
      "endDate": "2018-06-11T11:16:58.500031+03:00"
    }, 
    "signingPeriod": {
      "startDate": "2018-06-11T11:16:58.058569+03:00", 
      "endDate": "2018-06-11T11:57:14.851583+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-06-11T11:16:57.220195+03:00", 
      "endDate": "2018-06-11T11:16:58.500031+03:00"
    }, 
    "bid_id": "6e61c6ec3a544db4a2550e68c58ad0b7", 
    "value": {
      "currency": "UAH", 
      "amount": 300.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-06-11T11:16:58.514774+03:00", 
    "id": "d70ffc5e83e14d02963ce093b2689b9b"
  }
}

