PATCH /api/2.4/auctions/84b47bb9907e49fea639a06d4d2bd026/contracts/a0f6cb3f113243129b14be5a00e28c2e?acc_token=7fe14b58a7324881baa92bad83f2b3c9 HTTP/1.0
Authorization: Basic YnJva2VyMzo=
Content-Length: 60
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "dateSigned": "2018-06-11T16:35:41.726445+03:00"
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "contract signed", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/0514dbbc3b494776859b9cc99f55bec3?KeyID=172d32c8&Signature=z%2F9ggZXRc2VBBrVYK3FV0DYkAhOKLSKYNqa%2FaJx%2F9cwTnsK6e2%2F0PBvylJnk5s4FyGGijKepAH%2FU5GzFSoW6DQ%253D%253D", 
        "title": "contract_signed.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-06-11T16:35:41.558740+03:00", 
        "documentType": "contractSigned", 
        "dateModified": "2018-06-11T16:35:41.558766+03:00", 
        "id": "0998e140acd54e18a4a55c28bb3c4cdd"
      }
    ], 
    "signingPeriod": {
      "startDate": "2018-06-11T16:35:41.133133+03:00", 
      "endDate": "2018-06-11T17:15:44.646234+03:00"
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "66113000-5"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "e5be8d9cc4ac4505bd7bc1f0867a9f83", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "dateSigned": "2018-06-11T16:35:41.726445+03:00", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-06-11T16:35:41.390965+03:00", 
    "awardID": "494b2265301e441889f243b820967056", 
    "id": "a0f6cb3f113243129b14be5a00e28c2e", 
    "contractID": "UA-EA-2018-06-11-000001-1"
  }
}

