GET /api/2.4/auctions/a30fbb0cdfaa4885b5948e188dcb1710/contracts/f0ce720b32d340ebb1a52fc8db59f6f5/documents HTTP/1.0
Authorization: Basic YnJva2VyMzo=
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/367fe3af04b242848232419261374baa?KeyID=172d32c8&Signature=E%2F5ub4Q5kHBfy1nnKK66gQJPjoPm2l%2Fsro0TbvSckyYgv74YxRnJtw5XiINFzeNE1WkpEcvwy1AmY9e4gJacDQ%253D%253D", 
      "title": "contract_signed.pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-06-11T12:16:52.632496+03:00", 
      "dateModified": "2018-06-11T12:16:52.632550+03:00", 
      "id": "1510f528e39a4b21aea6e6bb33e6df36"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/msword", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/8136aa577e8c49538f02cc420c3951fb?KeyID=172d32c8&Signature=1PMQSZ2Dpbwv4RkAzQeDFeRUGFMNc9QMqApZj7XHnWklRDfGibYudcFPm0UHcHFou49P6b5SoK6RzpnhluXKBw%253D%253D", 
      "title": "contract_second_document.doc", 
      "documentOf": "tender", 
      "datePublished": "2018-06-11T12:16:52.788405+03:00", 
      "dateModified": "2018-06-11T12:16:52.788439+03:00", 
      "id": "1708e731a17848db807c14666f84c6cf"
    }
  ]
}

