POST /api/2.4/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyMzo=
Content-Length: 2003
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "футляри до державних нагород", 
    "submissionMethodDetails": "test submissionMethodDetails", 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "tenderAttempts": 1, 
    "procurementMethodType": "Swiftsure", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "auctionPeriod": {
      "startDate": "2018-06-21"
    }, 
    "items": [
      {
        "classification": {
          "scheme": "CPV", 
          "id": "66113000-5", 
          "description": "Земельні ділянки"
        }, 
        "quantity": 5, 
        "description": "Земля для військовослужбовців", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }
      }
    ]
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/6a61cb11a28d4d408c7334a17f669809
X-Content-Type-Options: nosniff

{
  "access": {
    "transfer": "dfa270c9839549ea8590f8f0f31fbae4", 
    "token": "5b4074736f894c36af6e4eb02ba91725"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-06-07-000001", 
    "minNumberOfQualifiedBids": 1, 
    "enquiryPeriod": {
      "startDate": "2018-06-07T17:50:21.723292+03:00", 
      "endDate": "2018-06-20T23:59:50+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2018-06-20T23:59:50+03:00", 
    "awardCriteria": "highestCost", 
    "owner": "broker3", 
    "id": "6a61cb11a28d4d408c7334a17f669809", 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2018-06-07T17:50:21.726789+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2018-06-07T17:50:21.723292+03:00", 
      "endDate": "2018-06-20T23:59:50+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2018-06-21T00:00:00+03:00"
    }, 
    "procurementMethodType": "Swiftsure", 
    "date": "2018-06-07T17:50:21.723292+03:00", 
    "submissionMethodDetails": "test submissionMethodDetails", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "66113000-5"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "34263f6ab8b2493ca40467eb67785445", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

