GET /api/2.4/auctions/97220a271daa48faaae51d29771fbb88/bids/a509415f03f9484aa644f3afae62fb59?acc_token=9345d09074cb4c01b2983fbb8d7c1bf2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/97220a271daa48faaae51d29771fbb88/bids/a509415f03f9484aa644f3afae62fb59/documents/ab22c78948584178bbb0b363801118e6?download=c892a93772af4941be65e3d3e900c91f", 
        "title": "Proposal.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-06-11T16:35:43.442548+03:00", 
        "dateModified": "2018-06-11T16:35:43.442574+03:00", 
        "id": "ab22c78948584178bbb0b363801118e6"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-06-11T16:35:43.343189+03:00", 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "owner": "broker", 
    "id": "a509415f03f9484aa644f3afae62fb59", 
    "participationUrl": "https://auction.auction.url/for_bid/a509415f03f9484aa644f3afae62fb59"
  }
}

