POST /api/2.4/auctions/84b47bb9907e49fea639a06d4d2bd026/awards/494b2265301e441889f243b820967056/documents?acc_token=7fe14b58a7324881baa92bad83f2b3c9 HTTP/1.0
Authorization: Basic YnJva2VyMzo=
Content-Length: 375
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d459b307e367467882738de4be3721dd?KeyID=172d32c8&Signature=KSGwiewxJ4bz52Get8ZCBQBUyJJHZCSW4VbGYCOhn1JUT3OdV4xrDOEB5lVVYrcSf0rDbWDUkC1wlTcI0p7OCg%3D%3D", 
    "title": "SignedAuctionProtocol.pdf", 
    "format": "application/pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "auctionProtocol"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/84b47bb9907e49fea639a06d4d2bd026/awards/494b2265301e441889f243b820967056/documents/00230b0270fe48199530593ef70c1a0c
X-Content-Type-Options: nosniff

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "auction_owner", 
    "title": "SignedAuctionProtocol.pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d459b307e367467882738de4be3721dd?KeyID=172d32c8&Signature=QXbB6NJV%2FIeHDRmSOuFD8IvrFfHUj%252BS%252BKthVPfk5oEK1D8Bk5myVyOUrx91BP8WPPPSUe%252Bpx5Drvb%2FUSYZ4%252BDw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-06-11T16:35:41.214901+03:00", 
    "documentType": "auctionProtocol", 
    "dateModified": "2018-06-11T16:35:41.214927+03:00", 
    "id": "00230b0270fe48199530593ef70c1a0c"
  }
}

