POST /api/2.4/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyMzo=
Content-Length: 2032
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "футляри до державних нагород", 
    "submissionMethodDetails": "test submissionMethodDetails", 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "tenderAttempts": 1, 
    "procurementMethodType": "Swiftsure", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "title_ru": "футляры к государственным наградам", 
    "auctionPeriod": {
      "startDate": "2018-06-25"
    }, 
    "items": [
      {
        "classification": {
          "scheme": "CAV", 
          "id": "06000000-2", 
          "description": "Земельні ділянки"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "b746e188c5b941dd8ab02e4bc8d1eef3", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "title_en": "Cases with state awards"
  }
}

