POST /api/2.4/auctions/dacad1ac9d9144ebadfd7940cd7d5d96/contracts/76e9f95b874b4846977f74b588bdc6dd/prolongations?acc_token=7539b5dc70b54aa3a4564c54d8d836b2 HTTP/1.0
Authorization: Basic YnJva2VyMzo=
Content-Length: 172
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "decisionID": "ZM-937-99-92", 
    "reason": "other", 
    "documents": [], 
    "description": "Prolongation description", 
    "datePublished": "2018-06-11T12:29:42.322295+03:00"
  }
}

